#!/bin/bash

echo $1
echo $2
echo $3

mkdir .outputdir
cd .outputdir
git clone git@github.com:3rv/$2.git
git rm -r
cd ..
cp $1 .outputdir/artifact
cd .outputdir
unzip artifact
rm artifact
git add --all
git commit -m "$3"
git push -f origin master
cd ..
rm -r .outputdir

